image: linuturk/pelican
script:
  - make -C $DRONE_BUILD_DIR html
publish:
    swift:
      username: {{raxUsername}}
      password: {{raxApikey}}
      auth_url: https://identity.api.rackspacecloud.com/v2.0
      region: DFW
      container: albush.com
      source: $DRONE_BUILD_DIR/output
