version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.27
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: hugo -v -s ~/project
      - run:
          name: "Test Website"
          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore
  deploy:
    docker:
      - image: cibuilds/aws
    steps:
      - checkout
      - run:
          name: "Upload to S3"
          command: aws s3 sync ~/project/public --region us-west-1 s3://albush.com/ --delete
      - run:
          name: "Invalidate CloudFront"
          command: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /index.html

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
