version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: hugo -v -s ~/project
      - persist_to_workspace:
          root: ~/project
          paths:
            - public
  deploy:
    docker:
      - image: cibuilds/aws
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Upload to Production - skip static files"
          command: aws s3 sync --acl "public-read" --storage-class "REDUCED_REDUNDANCY" ~/project/public/ s3://${BUCKET}/ --exclude 'images/*' --exclude 'scss/*'
      - run:
          name: "Copy and cache static files"
          command: |
            aws s3 sync --cache-control "max-age=2592000" --acl "public-read" --storage-class "REDUCED_REDUNDANCY" ~/project/public/images/ s3://${BUCKET}/images/
            aws s3 sync --cache-control "max-age=2592000" --acl "public-read" --storage-class "REDUCED_REDUNDANCY" ~/project/public/css/ s3://${BUCKET}/scss/
      - run:
          name: "Invalidate CloudFront"
          command: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /index.html

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
