theme="tale-hugo"
BaseURL = "//albush.com/"
languageCode = "en-us"
title = "Alan Bush"
paginate = 6 # To specify a multiple of 3

[author]
  author = "Alan Bush"
  email = "al@albush.com"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
  url = "/post/"
    weight = 2
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    title = "Portfolio"
    url = "/portfolio/"
    weight = 3

[params]
  Author = "Alan Bush"
  dateform = "January 2, 2006"
  logo      = "/images/ab3head.svg"
  phone     = "+1 210-704-7319"
  copyright = "albush"
  email     = "al@albush.com"
  description = "Nerd. Proponent of: Work from anywhere, coffee, beer, my face on coffee mugs, [improv comedy](https://cszsa.com). Not a fan of dongles."
  # optional
  analytics = "UA-15275173-7"
    [params.social]
      github      = "albush"
      facebook        = "alan.bush"
      facebook_admin  = "1554398007"  # This needs to be a page admin to get domain insights
      twitter     = "alanbush"
      twitter_domain  = "albush.com" # This domain shows in twitter cards as "View on `twitter_domain`"
      googleplus      = "+AlanBush"
      instagram       = "youcancallmealbush"
      linkedin        = "adbush"
    [params.authors]
      [params.authors.alan]
      name          = "Alan Bush"
      thumbnail     = "/images/ab3head.svg"
      images        = [
                      "http://drops.albush.com/bush_alan_04_small.jpg",
                    ]
      bio           = "Alan Bush is a nerd for hire by day, and a father and comedian by night. Alan likes beer, coffee, puns and the Kansas City Royals. He dislikes writing about himself in the third person."
      email         = "al@albush.com"
        [params.authors.Alan.social]
        name = "Alan Bush"
        github      = "albush"
        facebook        = "alan.bush"
        facebook_admin  = "1554398007"  # This needs to be a page admin to get domain insights
        twitter     = "alanbush"
        twitter_domain  = "albush.com" # This domain shows in twitter cards as "View on `twitter_domain`"
        googleplus      = "+AlanBush"
        instagram       = "youcancallmealbush"
        linkedin        = "adbush"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  android = "Android"
