theme="hugo-zen"
BaseURL = "//albush.com"
languageCode = "en-us"
title = "Alan Bush"
MetaDataFormat = "yaml"
paginate = 6 # To specify a multiple of 3
# disqusShortname = "Your Disqus Name" # optional
[[menu.main]]
        name = "Blog Posts"
        # weight = -110
        identifier = "posts"
        url = "/post/"
[[menu.main]]
        name = "External Posts"
        # weight = -110
        identifier = "writings"
        url = "/writing/"
[[menu.main]]
        name = "Speaking"
        # weight = -110
        identifier = "speakings"
        url = "/speaking/"
[[menu.main]]
        name = "Bio"
        identifier = "about"
        url = "/about/"

[author]
  author = "Alan Bush"
  email = "al@albush.com"

[params]
  logo      = "/images/ab3head.svg"
  phone     = "+1 210-704-7319"
  copyright = "albush"
  # twitter   = "https://twitter.com/alanbush"
  # github    = "https://github.com/albush/"
  email     = "al@albush.com"
  # linkedin  = "//www.linkedin.com/in/adbush"
  description = "Mustachioed [Nerd-For-Hire](//resume.albush.com) by day; Daddy, Writer and [Improvisor](//cszsa.com) by night. Host of [Office Hours Podcast](//ohpodcast.com), and the [SATechDad Podcast](//satechdad.com)."
  # optional
  analytics = "UA-15275173-7"
    [params.social]
      github      = "albush"
      facebook        = "alan.bush"
      facebook_admin  = "1554398007"  # This needs to be a page admin to get domain insights
      twitter     = "alanbush"
      twitter_domain  = "albush.com" # This domain shows in twitter cards as "View on `twitter_domain`"
      googleplus      = "+AlanBush"
      instagram       = "youcancallmealbush"
      # youtube     = ""
      linkedin        = "adbush"
    [params.authors]
      [params.authors.alan]
      name          = "Alan Bush"
      thumbnail     = "//2.gravatar.com/avatar/4b434a5f9b17613e7eae559726e31b99"
      images        = [
                      "http://drops.albush.com/bush_alan_04_small.jpg",
                    ]
      bio           = "Alan Bush is a nerd for hire by day, and a daddy and comedian by night. Alan likes beer, coffee, puns and the Kansas City Royals. He dislikes writing about himself in the third person."
      email         = "al@albush.com"
        [params.authors.Alan.social]
        name = "Alan Bush"
        github      = "albush"
        facebook        = "alan.bush"
        facebook_admin  = "1554398007"  # This needs to be a page admin to get domain insights
        twitter     = "alanbush"
        twitter_domain  = "albush.com" # This domain shows in twitter cards as "View on `twitter_domain`"
        googleplus      = "+AlanBush"
        instagram       = "youcancallmealbush"
        linkedin        = "adbush"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  android = "Android"
