theme="hugo-zen"
baseurl = "http://albush.com"
languageCode = "en-us"
title = "Alan Bush"
MetaDataFormat = "yaml"
paginate = 6 # To specify a multiple of 3
# disqusShortname = "Your Disqus Name" # optional
copyright = "© 2015 Alan Bush"
[[menu.main]]
        name = "Blog Posts"
        # weight = -110
        identifier = "posts"
        url = "/post/"
[[menu.main]]
        name = "External Posts"
        # weight = -110
        identifier = "writings"
        url = "/writing/"
[[menu.main]]
        name = "Speaking"
        # weight = -110
        identifier = "speakings"
        url = "/speaking/"
[[menu.main]]
        name = "Bio"
        identifier = "about"
        url = "/about/"

[author]
  author = "Alan Bush"
  email = "al@albush.com"

[params]
  logo      = "http://drops.albush.com/ab3head.svg"
  phone     = "+1 210-704-7319"
  copyright = "albush All rights reserved."
  twitter   = "https://twitter.com/alanbush"
  github    = "https://github.com/albush/"
  email     = "al@albush.com"
  linkedin  = "http://www.linkedin.com/in/adbush"
  description = "Mustachioed Cloud Technology Mentor by day; Daddy, Husband and Improvisor by night." # optional
  analytics = "UA-15275173-7"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  android = "Android"
