theme="material-design"
baseurl = "albush.com"
languageCode = "en-us"
title = "Alan Bush"
MetaDataFormat = "toml"
paginate = 6 # To specify a multiple of 3
# disqusShortname = "Your Disqus Name" # optional
copyright = "© 2015 Alan Bush"

[params]
  description = "Mustachioed Cloud Technology Mentor by day; Daddy, Husband and Improvisor by night." # optional
  twitter = "alanbush" # optional
  github = "albush" # optional
  # facebook = "Your facebook Name" # optional
  gplus = "AlanBush" # optional
  linkedin = "adbush" # optional
  headerCover = "http://share.albush.com/fyKF4BgPAO/background.jpg" # optional
  footerCover = "http://drops.albush.com/background-cover.jpg" # optional
  # googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
