[Site]
  languageCode = "en-us"
  contentdir = "content"
  publishdir = "public"
  builddrafts = false
  baseurl = "http://albush.com/"
  canonifyurls = true
  Title = "Alan Bush"
  author = "Alan Bush"

[indexes]
   category = "categories"
   tag = "tags"
[Params]
  description = "Mustachioed Cloud Technology Mentor by day; Daddy, Husband and Improvisor by night."
  AuthorName = "Alan"
  github = "albush"
  twitter = "alanbush"
  email = "al@albush.com"
  resume = "//resume.albush.com"
  linkedin = "adbush"
  cover = "/images/background-cover.jpg"
  logo = "//drops.albush.com/ab3head.png"
  about = "/about"
  disqus = "albush"